import { describe, expect, it } from 'vitest'
import { activeClipsAt, compositionDuration, createComposition, deleteClip, detachClip, moveClip, nextActiveClip, reorderTrack, setAppearance, setCrop, setEnabled, setPlaybackRate, setTransform, sourceTimeAt, splitClip, timelineTimeAt, trimClip } from '../../src/components/video-editor/composition/engine/clip-engine'
import { type Clip, type ClipComposition } from '../../src/components/video-editor/composition/engine/clip-types'

const asset = { id: 'recording', kind: 'video' as const, name: 'Recording', durationMs: 10_000, width: 1920, height: 1080, src: 'recording.mp4', origin: 'session' as const }
const clip = (id: string, kind: Clip['kind'] = 'screen', overrides: Partial<Clip> = {}): Clip => ({ id, kind, assetId: kind === 'caption' ? null : 'recording', caption: kind === 'caption' ? { text: 'Hello', style: {} } : null, timelineStartMs: 1_000, timelineDurationMs: 4_000, sourceInMs: 200, sourceDurationMs: 4_000, playbackRate: 1, enabled: true, trackOrder: 0, ...overrides })
const linked = (): ClipComposition => createComposition([asset], [clip('screen'), clip('camera', 'webcam'), clip('audio', 'system-audio')], [{ id: 'recording-group', clipIds: ['screen', 'camera', 'audio'] }])

describe('clip composition engine', () => {
  it('uses clips and assets as the only schema', () => expect(createComposition()).toEqual({ schemaVersion: 3, assets: [], clips: [], groups: [] }))
  it('maps timeline and source times using the clip rate', () => { const value = clip('a', 'screen', { playbackRate: 2 }); expect(sourceTimeAt(value, 1_500)).toBe(1_200); expect(timelineTimeAt(value, 1_200)).toBe(1_500); expect(sourceTimeAt(value, 5_001)).toBeNull() })
  it('returns enabled active clips in track order and calculates duration', () => { const value = createComposition([asset], [clip('back', 'image', { trackOrder: 2, playbackRate: 1 }), clip('front', 'screen', { trackOrder: 1 }), clip('hidden', 'audio', { enabled: false, timelineStartMs: 9_000 })]); expect(activeClipsAt(value, 1_100).map((entry) => entry.id)).toEqual(['front', 'back']); expect(compositionDuration(value)).toBe(5_000) })
  it('moves and changes rate for the current linked group only', () => { const changed = setPlaybackRate(moveClip(linked(), 'screen', 2_500), 'camera', 1.25); expect(changed.clips.every((entry) => entry.timelineStartMs === 2_500 && entry.timelineDurationMs === 3_200)).toBe(true) })
  it('trims non-destructively within source bounds and restores on reverse trim', () => { const trimmed = trimClip(linked(), 'screen', 'start', 2_000); expect(trimmed.clips[0]).toMatchObject({ timelineStartMs: 2_000, sourceInMs: 1_200, sourceDurationMs: 3_000 }); const restored = trimClip(trimmed, 'screen', 'start', 1_000); expect(restored.clips[0]).toMatchObject({ timelineStartMs: 1_000, sourceInMs: 200, sourceDurationMs: 4_000 }) })
  it('extends an end trim again without fabricating a new source range', () => { const shortened = trimClip(linked(), 'screen', 'end', 3_000); const restored = trimClip(shortened, 'screen', 'end', 12_000); expect(restored.clips[0]).toMatchObject({ timelineDurationMs: 9_800, sourceDurationMs: 9_800 }); expect(restored.clips[0]?.sourceInMs).toBe(200) })
  it('splits a group into independent left and right groups', () => { const ids = ['screen-right', 'camera-right', 'audio-right', 'right-group']; let index = 0; const split = splitClip(linked(), 'screen', 3_000, () => ids[index++]!); expect(split.groups).toEqual([{ id: 'recording-group', clipIds: ['screen', 'camera', 'audio'] }, { id: 'right-group', clipIds: ['screen-right', 'camera-right', 'audio-right'] }]); expect(setPlaybackRate(split, 'screen-right', 2).clips.find((entry) => entry.id === 'screen')).toMatchObject({ playbackRate: 1 }) })
  it('detaches a track permanently from group timing', () => { const edited = setPlaybackRate(moveClip(detachClip(linked(), 'camera'), 'camera', 5_000), 'camera', 2); expect(edited.clips.find((entry) => entry.id === 'camera')).toMatchObject({ timelineStartMs: 5_000, playbackRate: 2 }); expect(edited.clips.find((entry) => entry.id === 'screen')).toMatchObject({ timelineStartMs: 1_000, playbackRate: 1 }) })
  it('ripples a deleted group and resolves the next active clip', () => { const composition = createComposition([asset], [...linked().clips, clip('later', 'video', { timelineStartMs: 6_000 })], linked().groups); const deleted = deleteClip(composition, 'screen'); expect(deleted.clips.map((entry) => entry.id)).toEqual(['later']); expect(deleted.clips[0]?.timelineStartMs).toBe(2_000); expect(nextActiveClip(deleted, 0)?.id).toBe('later') })
  it('keeps appearance, crop and transform local to a split clip', () => { const split = splitClip(linked(), 'screen', 3_000, (() => { let n = 0; return () => `id-${n++}` })()); const changed = setCrop(setTransform(setAppearance(split, 'screen', { frame: 'safari' }), 'screen', { x: .1, y: .2, width: .6, height: .7 }), 'screen', { x: .2, y: .2, width: .5, height: .5 }); expect(changed.clips.find((entry) => entry.id === 'id-0')).not.toHaveProperty('appearance'); expect(changed.clips.find((entry) => entry.id === 'screen')).toMatchObject({ appearance: { frame: 'safari' }, crop: { x: .2, y: .2, width: .5, height: .5 } }) })
  it('rejects speed for images and enables captions through the common operation', () => { const composition = createComposition([asset], [clip('image', 'image'), clip('caption', 'caption')]); expect(() => setPlaybackRate(composition, 'image', 2)).toThrow(/speed/); expect(setEnabled(composition, 'caption', false).clips[1]?.enabled).toBe(false) })
  it('reorders tracks without changing timeline data', () => { const changed = reorderTrack(linked(), 'camera', 4); expect(changed.clips.find((entry) => entry.id === 'camera')).toMatchObject({ trackOrder: 4, timelineStartMs: 1_000 }) })
})
