import { DEFAULT_GRADIENT_RECIPE } from './gradient-schema.js';
import type { GradientRecipe, GradientLayerEffect, GradientPreset } from './gradient-types';

// Palettes and authored geometry from BEBE-ui's Gradient Studio.
const presets = [
  {
    id: 'aurora',
    name: 'Aurora',
    colors: ['#2457ff', '#6335ff', '#7aa5ff', '#bde9ff'],
    background: '#f1f5ff',
    mode: 'flow',
    seed: 12,
    rotation: -25,
    space: 55,
    distortion: 55,
    softness: 35,
    folds: 30,
  },
  {
    id: 'ember',
    name: 'Ember',
    colors: ['#ff571c', '#f72c4b', '#98244c', '#ffb885'],
    background: '#fff4e8',
    mode: 'flow',
    seed: 21,
    rotation: 32,
    space: 58,
    distortion: 62,
    softness: 40,
    folds: 35,
  },
  {
    id: 'bloom',
    name: 'Bloom',
    colors: ['#f52aa2', '#ab32ee', '#703cff', '#edabff'],
    background: '#fff2fc',
    mode: 'silk',
    seed: 8,
    rotation: -35,
    space: 60,
    distortion: 48,
    softness: 48,
    folds: 45,
  },
  {
    id: 'tide',
    name: 'Tide',
    colors: ['#00ba96', '#00b6cc', '#0763ee', '#92eddb'],
    background: '#eafff7',
    mode: 'flow',
    seed: 42,
    rotation: 15,
    space: 58,
    distortion: 68,
    softness: 42,
    folds: 20,
  },
  {
    id: 'nocturne',
    name: 'Nocturne',
    colors: ['#343bff', '#853dff', '#ed65ce', '#aaa9ff'],
    background: '#0c1027',
    mode: 'silk',
    seed: 16,
    rotation: -35,
    space: 60,
    distortion: 65,
    softness: 30,
    folds: 60,
  },
  {
    id: 'sunrise',
    name: 'Sunrise',
    colors: ['#ffac23', '#ff6940', '#f84581', '#ffd29c'],
    background: '#fff9ee',
    mode: 'flow',
    seed: 5,
    rotation: -12,
    space: 55,
    distortion: 40,
    softness: 50,
    folds: 15,
  },
] satisfies (Partial<GradientRecipe> & { id: string; name: string })[];
export const GRADIENT_PRESETS: GradientPreset[] = presets.map(({ id, name, ...recipe }) => ({
  id,
  name,
  recipe: { ...DEFAULT_GRADIENT_RECIPE, ...recipe },
}));
export function createGradientEffect(id: string): GradientLayerEffect {
  return {
    id,
    kind: 'gradient',
    enabled: true,
    opacity: 100,
    blendMode: 'source-over',
    recipe: structuredClone(GRADIENT_PRESETS[0]!.recipe),
  };
}
