import { COMPOSITION_SCHEMA_VERSION, MAX_PLAYBACK_RATE, MIN_PLAYBACK_RATE, type Clip, type ClipAppearance, type ClipComposition, type ClipCrop, type ClipGroup, type ClipTransform, type IdFactory, type TrimEdge } from './clip-types'

export class CompositionEngineError extends Error {}
const createId: IdFactory = () => crypto.randomUUID()
const finite = (value: number) => Number.isFinite(value)
const rounded = (value: number) => Math.round(value)
const clone = (value: ClipComposition): ClipComposition => structuredClone(value)
const clipEnd = (clip: Clip) => clip.timelineStartMs + clip.timelineDurationMs
const isVisual = (clip: Clip) => !['audio', 'system-audio', 'microphone'].includes(clip.kind)
const isRateAdjustable = (clip: Clip) => clip.kind !== 'image' && clip.kind !== 'caption'
function requireClip(composition: ClipComposition, clipId: string): Clip { const clip = composition.clips.find((entry) => entry.id === clipId); if (!clip) throw new CompositionEngineError(`Unknown clip: ${clipId}`); return clip }
function groupFor(composition: ClipComposition, clipId: string): ClipGroup | undefined { return composition.groups.find((group) => group.clipIds.includes(clipId)) }
function targetIds(composition: ClipComposition, clipId: string): string[] { return groupFor(composition, clipId)?.clipIds ?? [clipId] }
function ordered(clips: Clip[]): Clip[] { return [...clips].sort((a, b) => a.trackOrder - b.trackOrder || a.id.localeCompare(b.id)) }
function nextWith(composition: ClipComposition, mutate: (next: ClipComposition) => void): ClipComposition { const next = clone(composition); mutate(next); validateComposition(next); return next }
function clampRect(rect: ClipTransform | ClipCrop): ClipTransform { if (![rect.x, rect.y, rect.width, rect.height].every(finite) || rect.width <= 0 || rect.height <= 0) throw new CompositionEngineError('Invalid rectangle.'); return { x: Math.max(0, Math.min(1, rect.x)), y: Math.max(0, Math.min(1, rect.y)), width: Math.max(.001, Math.min(1, rect.width)), height: Math.max(.001, Math.min(1, rect.height)) } }

export function createComposition(assets: ClipComposition['assets'] = [], clips: Clip[] = [], groups: ClipGroup[] = []): ClipComposition { const composition: ClipComposition = { schemaVersion: COMPOSITION_SCHEMA_VERSION, assets: structuredClone(assets), clips: structuredClone(clips), groups: structuredClone(groups) }; validateComposition(composition); return composition }
export function validateComposition(composition: ClipComposition): void {
  if (!composition || composition.schemaVersion !== COMPOSITION_SCHEMA_VERSION || !Array.isArray(composition.assets) || !Array.isArray(composition.clips) || !Array.isArray(composition.groups)) throw new CompositionEngineError('Invalid composition schema.')
  const assetIds = new Set<string>(); for (const asset of composition.assets) { if (!asset || !asset.id || assetIds.has(asset.id) || !['video', 'audio', 'image'].includes(asset.kind) || !finite(asset.durationMs) || asset.durationMs < 0) throw new CompositionEngineError('Invalid asset.'); assetIds.add(asset.id) }
  const ids = new Set<string>(); for (const clip of composition.clips) { if (!clip || !clip.id || ids.has(clip.id) || !['screen', 'webcam', 'system-audio', 'microphone', 'video', 'audio', 'image', 'caption'].includes(clip.kind)) throw new CompositionEngineError('Invalid clip identity.'); ids.add(clip.id); if (![clip.timelineStartMs, clip.timelineDurationMs, clip.sourceInMs, clip.sourceDurationMs, clip.playbackRate, clip.trackOrder].every(finite) || clip.timelineStartMs < 0 || clip.timelineDurationMs <= 0 || clip.sourceInMs < 0 || clip.sourceDurationMs <= 0) throw new CompositionEngineError('Invalid clip timing.'); if (clip.kind === 'caption' ? clip.assetId !== null || !clip.caption : clip.assetId === null || !assetIds.has(clip.assetId) || clip.caption !== null) throw new CompositionEngineError('Invalid clip content.'); if (!isRateAdjustable(clip) && clip.playbackRate !== 1) throw new CompositionEngineError('Images and captions cannot change speed.'); if (clip.playbackRate < MIN_PLAYBACK_RATE || clip.playbackRate > MAX_PLAYBACK_RATE) throw new CompositionEngineError('Playback rate must be between 0.25x and 4x.'); const asset = clip.assetId ? composition.assets.find((entry) => entry.id === clip.assetId) : undefined; if (asset && clip.sourceInMs + clip.sourceDurationMs > asset.durationMs) throw new CompositionEngineError('Clip exceeds its source asset.') }
  const grouped = new Set<string>(); for (const group of composition.groups) { if (!group.id || group.clipIds.length < 2 || group.clipIds.some((id) => !ids.has(id) || grouped.has(id))) throw new CompositionEngineError('Invalid clip group.'); group.clipIds.forEach((id) => grouped.add(id)) }
}
export function compositionDuration(composition: ClipComposition): number { return Math.max(0, ...composition.clips.filter((clip) => clip.enabled).map(clipEnd)) }
export function sourceTimeAt(clip: Clip, timelineMs: number): number | null { if (!finite(timelineMs) || timelineMs < clip.timelineStartMs || timelineMs > clipEnd(clip)) return null; return rounded(clip.sourceInMs + (timelineMs - clip.timelineStartMs) * clip.playbackRate) }
export function timelineTimeAt(clip: Clip, sourceMs: number): number | null { if (!finite(sourceMs) || sourceMs < clip.sourceInMs || sourceMs > clip.sourceInMs + clip.sourceDurationMs) return null; return rounded(clip.timelineStartMs + (sourceMs - clip.sourceInMs) / clip.playbackRate) }
export function activeClipsAt(composition: ClipComposition, timelineMs: number): Clip[] { return ordered(composition.clips.filter((clip) => clip.enabled && sourceTimeAt(clip, timelineMs) !== null)) }
export function visibleClipsForTrack(composition: ClipComposition, trackOrder: number): Clip[] { return ordered(composition.clips.filter((clip) => clip.trackOrder === trackOrder)) }
export function nextActiveClip(composition: ClipComposition, timelineMs: number): Clip | null { return ordered(composition.clips.filter((clip) => clip.enabled && clip.timelineStartMs >= timelineMs))[0] ?? null }
export function moveClip(composition: ClipComposition, clipId: string, timelineStartMs: number): ClipComposition { if (!finite(timelineStartMs) || timelineStartMs < 0) throw new CompositionEngineError('Invalid timeline position.'); return nextWith(composition, (next) => { const delta = rounded(timelineStartMs) - requireClip(next, clipId).timelineStartMs; targetIds(next, clipId).forEach((id) => { requireClip(next, id).timelineStartMs += delta }) }) }
export function setPlaybackRate(composition: ClipComposition, clipId: string, playbackRate: number): ClipComposition { if (!finite(playbackRate) || playbackRate < MIN_PLAYBACK_RATE || playbackRate > MAX_PLAYBACK_RATE) throw new CompositionEngineError('Playback rate must be between 0.25x and 4x.'); return nextWith(composition, (next) => targetIds(next, clipId).forEach((id) => { const clip = requireClip(next, id); if (!isRateAdjustable(clip)) throw new CompositionEngineError('This clip has no speed control.'); clip.playbackRate = playbackRate; clip.timelineDurationMs = rounded(clip.sourceDurationMs / playbackRate) })) }
export function trimClip(composition: ClipComposition, clipId: string, edge: TrimEdge, timelineMs: number): ClipComposition { const source = requireClip(composition, clipId); if (!finite(timelineMs)) throw new CompositionEngineError('Invalid trim position.'); return nextWith(composition, (next) => targetIds(next, clipId).forEach((id) => { const clip = requireClip(next, id); const requested = rounded(timelineMs - source.timelineStartMs); if (edge === 'start') { const change = Math.max(-(clip.sourceInMs / clip.playbackRate), Math.min(requested, clip.timelineDurationMs - 1)); clip.timelineStartMs += change; clip.timelineDurationMs -= change; clip.sourceInMs += rounded(change * clip.playbackRate); clip.sourceDurationMs -= rounded(change * clip.playbackRate) } else { const asset = clip.assetId ? next.assets.find((entry) => entry.id === clip.assetId) : undefined; const available = asset ? (asset.durationMs - clip.sourceInMs) / clip.playbackRate : clip.sourceDurationMs / clip.playbackRate; const duration = Math.max(1, Math.min(requested, available)); clip.timelineDurationMs = duration; clip.sourceDurationMs = rounded(duration * clip.playbackRate) } })) }
export function splitClip(composition: ClipComposition, clipId: string, timelineMs: number, idFactory: IdFactory = createId): ClipComposition { const source = requireClip(composition, clipId); if (!finite(timelineMs) || timelineMs <= source.timelineStartMs || timelineMs >= clipEnd(source)) throw new CompositionEngineError('Split must be inside the clip.'); return nextWith(composition, (next) => { const group = groupFor(next, clipId); const ids = targetIds(next, clipId); const offset = rounded(timelineMs - source.timelineStartMs); const rightIds: string[] = []; for (const id of ids) { const clip = requireClip(next, id); const sourceOffset = rounded(offset * clip.playbackRate); const right: Clip = { ...clip, id: idFactory(), timelineStartMs: clip.timelineStartMs + offset, timelineDurationMs: clip.timelineDurationMs - offset, sourceInMs: clip.sourceInMs + sourceOffset, sourceDurationMs: clip.sourceDurationMs - sourceOffset }; clip.timelineDurationMs = offset; clip.sourceDurationMs = sourceOffset; next.clips.push(right); rightIds.push(right.id) }; if (group) next.groups.push({ id: idFactory(), clipIds: rightIds }) }) }
export function deleteClip(composition: ClipComposition, clipId: string): ClipComposition { return nextWith(composition, (next) => { const ids = targetIds(next, clipId); const source = requireClip(next, clipId); next.clips = next.clips.filter((clip) => !ids.includes(clip.id)).map((clip) => clip.timelineStartMs >= source.timelineStartMs ? { ...clip, timelineStartMs: Math.max(0, clip.timelineStartMs - source.timelineDurationMs) } : clip); next.groups = next.groups.filter((group) => !ids.some((id) => group.clipIds.includes(id))) }) }
export function setEnabled(composition: ClipComposition, clipId: string, enabled: boolean): ClipComposition { return nextWith(composition, (next) => { requireClip(next, clipId).enabled = Boolean(enabled) }) }
export function setAppearance(composition: ClipComposition, clipId: string, patch: Partial<ClipAppearance>): ClipComposition { return nextWith(composition, (next) => { const clip = requireClip(next, clipId); if (!isVisual(clip)) throw new CompositionEngineError('Audio clips have no appearance.'); clip.appearance = { ...clip.appearance, ...patch } }) }
export function setTransform(composition: ClipComposition, clipId: string, transform: ClipTransform): ClipComposition { return nextWith(composition, (next) => { const clip = requireClip(next, clipId); if (!isVisual(clip)) throw new CompositionEngineError('Audio clips have no visual transform.'); clip.transform = clampRect(transform) }) }
export function setCrop(composition: ClipComposition, clipId: string, crop: ClipCrop): ClipComposition { return nextWith(composition, (next) => { const clip = requireClip(next, clipId); if (!isVisual(clip)) throw new CompositionEngineError('Audio clips have no crop.'); clip.crop = clampRect(crop) }) }
export function detachClip(composition: ClipComposition, clipId: string): ClipComposition { return nextWith(composition, (next) => { const group = groupFor(next, clipId); if (!group) return; group.clipIds = group.clipIds.filter((id) => id !== clipId); next.groups = next.groups.filter((entry) => entry.clipIds.length >= 2) }) }
export function reorderTrack(composition: ClipComposition, clipId: string, trackOrder: number): ClipComposition { if (!Number.isInteger(trackOrder) || trackOrder < 0) throw new CompositionEngineError('Invalid track order.'); return nextWith(composition, (next) => { requireClip(next, clipId).trackOrder = trackOrder }) }
export function setVolume(composition: ClipComposition, clipId: string, volume: number): ClipComposition { if (!finite(volume)) throw new CompositionEngineError('Invalid clip volume.'); return nextWith(composition, (next) => { const clip = requireClip(next, clipId); if (!['audio', 'system-audio', 'microphone'].includes(clip.kind)) throw new CompositionEngineError('Only audio clips have volume.'); clip.volume = Math.max(0, Math.min(200, volume)) }) }
export function setMirrored(composition: ClipComposition, clipId: string, isMirrored: boolean): ClipComposition { return nextWith(composition, (next) => { const clip = requireClip(next, clipId); if (!isVisual(clip)) throw new CompositionEngineError('Audio clips cannot be mirrored.'); clip.isMirrored = Boolean(isMirrored) }) }
export const setClipEnabled = setEnabled
export const transformClip = setTransform
export const clipsActiveAt = activeClipsAt
export const clipsVisibleForTrack = visibleClipsForTrack
export const resolveNextActiveClip = nextActiveClip
export const timelineToSourceMs = sourceTimeAt
export const sourceToTimelineMs = timelineTimeAt
