//! GStreamer owns decoding, composition, audio mixing, and encoding.
mod audio_clock;
pub mod change_types;
mod changes;
mod command_types;
mod composition;
mod composition_types;
pub mod controller;
pub mod effects;
pub mod frame_gate;
pub mod frame_gate_types;
pub mod gpu;
pub mod import_copy;
pub(crate) mod import_types;
pub mod pipeline;
pub mod plan;
pub mod plan_types;
pub mod preview;
pub mod preview_lease;
pub mod probe;
pub mod recording_effects;
mod retime;
pub mod scope_source_types;
pub mod scoped_pipeline;
pub mod scopes;
pub mod seek;
pub mod source_run_types;
pub mod source_runs;
pub(crate) mod thumbnail;
pub(crate) mod title;
pub mod transition_types;
pub mod transitions;
pub mod types;
pub mod visuals;
pub mod worker;
pub mod zoom;
