const { contextBridge, ipcRenderer } = require('electron')

const invoke = (command, payload) => ipcRenderer.invoke('capture:request', command, payload)

contextBridge.exposeInMainWorld('capture', Object.freeze({
  discover: () => invoke('discover'), capabilities: () => invoke('capabilities'), permissions: () => invoke('permissions'), formats: (sourceId) => invoke('formats', { source: sourceId }), prepare: (config) => invoke('prepare', { config }), startRecording: (options = {}) => invoke('start-default-recording', { options }), start: (config) => config ? invoke('start-recording', { config }) : invoke('start'), pause: () => invoke('pause'), resume: () => invoke('resume'), stop: () => invoke('stop'), status: () => invoke('status'),
  beginCameraSegment: (payload) => ipcRenderer.invoke('camera:begin-segment', payload), writeCameraSegment: (payload) => ipcRenderer.invoke('camera:write-segment', payload), finalizeCameraSegment: (payload) => ipcRenderer.invoke('camera:finalize-segment', payload), failCamera: (payload) => ipcRenderer.invoke('camera:fail', payload),
  beginMicrophoneSegment: (payload) => ipcRenderer.invoke('microphone:begin-segment', payload), writeMicrophoneSegment: (payload) => ipcRenderer.invoke('microphone:write-segment', payload), finalizeMicrophoneSegment: (payload) => ipcRenderer.invoke('microphone:finalize-segment', payload), failMicrophone: (payload) => ipcRenderer.invoke('microphone:fail', payload),
  beginSystemAudioSegment: (payload) => ipcRenderer.invoke('system-audio:begin-segment', payload), writeSystemAudioSegment: (payload) => ipcRenderer.invoke('system-audio:write-segment', payload), finalizeSystemAudioSegment: (payload) => ipcRenderer.invoke('system-audio:finalize-segment', payload), failSystemAudio: (payload) => ipcRenderer.invoke('system-audio:fail', payload),
  close: () => ipcRenderer.send('window:close'), minimize: () => ipcRenderer.send('window:minimize'), setWindowMode: (mode) => ipcRenderer.send('window:set-mode', mode), showHud: () => ipcRenderer.send('window:show-hud'), present: () => ipcRenderer.send('window:present'), maximize: () => ipcRenderer.send('window:maximize'), unmaximize: () => ipcRenderer.send('window:unmaximize'), toggleMaximize: () => ipcRenderer.send('window:toggleMaximize'), setPosition: (x, y) => ipcRenderer.send('window:setPosition', x, y), setSize: (width, height) => ipcRenderer.send('window:setSize', width, height), setSizeSmooth: (width, height) => ipcRenderer.send('window:setSizeSmooth', width, height), setInteractive: (v) => ipcRenderer.send('window:setInteractive', v), setRecorderTooltip: (visible) => ipcRenderer.send('window:set-recorder-tooltip', Boolean(visible)), dragStart: () => ipcRenderer.send('window:dragStart'), drag: () => ipcRenderer.send('window:drag'),
  getSources: (types) => ipcRenderer.invoke('window:getSources', types), getWindowBounds: () => ipcRenderer.invoke('window:bounds'), setCameraOverlayInteractive: (value) => ipcRenderer.send('camera-overlay:set-interactive', Boolean(value)), setCountdown: (seconds) => ipcRenderer.send('countdown:set', seconds), onCountdown: (listener) => { const callback = (_event, seconds) => listener(seconds); ipcRenderer.on('countdown:state', callback); return () => ipcRenderer.removeListener('countdown:state', callback) }, listProjects: () => ipcRenderer.invoke('projects:list'), getProjectEditorData: (projectId) => ipcRenderer.invoke('projects:editor-data', { projectId }), saveProjectZoomState: (projectId, zoom) => ipcRenderer.invoke('projects:save-zoom-state', { projectId, zoom }), createProject: (options = {}) => ipcRenderer.invoke('projects:create', options), renameProject: (projectId, name) => ipcRenderer.invoke('projects:rename', { projectId, name }), saveProjectThumbnail: (projectId, dataUrl) => ipcRenderer.invoke('projects:save-thumbnail', { projectId, dataUrl }), deleteProject: (projectId) => ipcRenderer.invoke('projects:delete', { projectId }),
  getProjectComposition: (projectId) => ipcRenderer.invoke('projects:composition', { projectId }), saveProjectComposition: (projectId, composition) => ipcRenderer.invoke('projects:save-composition', { projectId, composition }), pickProjectCompositionMedia: (projectId, kind) => ipcRenderer.invoke('projects:pick-composition-media', { projectId, kind }), saveProjectCompositionLayer: (projectId, layer) => ipcRenderer.invoke('projects:save-composition-layer', { projectId, layer }), deleteProjectCompositionLayer: (projectId, layerId) => ipcRenderer.invoke('projects:delete-composition-layer', { projectId, layerId }), moveProjectCompositionLayer: (projectId, layerId, targetIndex) => ipcRenderer.invoke('projects:move-composition-layer', { projectId, layerId, targetIndex }),
  whisperModels: () => ipcRenderer.invoke('whisper:models'), downloadWhisperModel: (modelId) => ipcRenderer.invoke('whisper:download', { modelId }), onWhisperProgress: (listener) => { const callback = (_event, progress) => listener(progress); ipcRenderer.on('whisper:progress', callback); return () => ipcRenderer.removeListener('whisper:progress', callback) },
  configureCameraOverlay: (state) => ipcRenderer.send('camera-overlay:configure', state), resizeCameraOverlay: (options) => ipcRenderer.invoke('camera-overlay:resize', options), toggleCameraSettings: () => ipcRenderer.send('camera-overlay:toggle-settings'), getCameraOverlayState: () => ipcRenderer.invoke('camera-overlay:state'), onCameraOverlayState: (listener) => { const callback = (_event, state) => listener(state); ipcRenderer.on('camera-overlay:state', callback); return () => ipcRenderer.removeListener('camera-overlay:state', callback) },
  beginExport: (options) => ipcRenderer.invoke('export:begin', options), writeExportChunk: (payload) => ipcRenderer.invoke('export:write', payload), finalizeExport: (jobId) => ipcRenderer.invoke('export:finalize', { jobId }), abortExport: (jobId) => ipcRenderer.invoke('export:abort', { jobId }),
}))
