const { contextBridge, ipcRenderer } = require('electron')

const invoke = (command, payload) => ipcRenderer.invoke('capture:request', command, payload)

contextBridge.exposeInMainWorld('capture', Object.freeze({
  discover: () => invoke('discover'), capabilities: () => invoke('capabilities'), permissions: () => invoke('permissions'), formats: (sourceId) => invoke('formats', { source: sourceId }), prepare: (config) => invoke('prepare', { config }), startRecording: (options = {}) => invoke('start-default-recording', { options }), start: (config) => config ? invoke('start-recording', { config }) : invoke('start'), pause: () => invoke('pause'), resume: () => invoke('resume'), stop: () => invoke('stop'), status: () => invoke('status'),
  beginCameraSegment: (payload) => ipcRenderer.invoke('camera:begin-segment', payload), writeCameraSegment: (payload) => ipcRenderer.invoke('camera:write-segment', payload), finalizeCameraSegment: (payload) => ipcRenderer.invoke('camera:finalize-segment', payload), failCamera: (payload) => ipcRenderer.invoke('camera:fail', payload),
  beginMicrophoneSegment: (payload) => ipcRenderer.invoke('microphone:begin-segment', payload), writeMicrophoneSegment: (payload) => ipcRenderer.invoke('microphone:write-segment', payload), finalizeMicrophoneSegment: (payload) => ipcRenderer.invoke('microphone:finalize-segment', payload), failMicrophone: (payload) => ipcRenderer.invoke('microphone:fail', payload),
  beginSystemAudioSegment: (payload) => ipcRenderer.invoke('system-audio:begin-segment', payload), writeSystemAudioSegment: (payload) => ipcRenderer.invoke('system-audio:write-segment', payload), finalizeSystemAudioSegment: (payload) => ipcRenderer.invoke('system-audio:finalize-segment', payload), failSystemAudio: (payload) => ipcRenderer.invoke('system-audio:fail', payload),
  close: () => ipcRenderer.send('window:close'), minimize: () => ipcRenderer.send('window:minimize'), setWindowMode: (mode) => ipcRenderer.send('window:set-mode', mode), present: () => ipcRenderer.send('window:present'), maximize: () => ipcRenderer.send('window:maximize'), unmaximize: () => ipcRenderer.send('window:unmaximize'), toggleMaximize: () => ipcRenderer.send('window:toggleMaximize'), setPosition: (x, y) => ipcRenderer.send('window:setPosition', x, y), setSize: (width, height) => ipcRenderer.send('window:setSize', width, height), setSizeSmooth: (width, height) => ipcRenderer.send('window:setSizeSmooth', width, height), setInteractive: (v) => ipcRenderer.send('window:setInteractive', v), dragStart: () => ipcRenderer.send('window:dragStart'), drag: () => ipcRenderer.send('window:drag'),
  getSources: (types) => ipcRenderer.invoke('window:getSources', types), listProjects: () => ipcRenderer.invoke('projects:list'), getProjectEditorData: (projectId) => ipcRenderer.invoke('projects:editor-data', { projectId }), saveProjectZoomState: (projectId, zoom) => ipcRenderer.invoke('projects:save-zoom-state', { projectId, zoom }), createProject: (options = {}) => ipcRenderer.invoke('projects:create', options), renameProject: (projectId, name) => ipcRenderer.invoke('projects:rename', { projectId, name }), saveProjectThumbnail: (projectId, dataUrl) => ipcRenderer.invoke('projects:save-thumbnail', { projectId, dataUrl }), deleteProject: (projectId) => ipcRenderer.invoke('projects:delete', { projectId }),
  beginExport: (options) => ipcRenderer.invoke('export:begin', options), writeExportChunk: (payload) => ipcRenderer.invoke('export:write', payload), finalizeExport: (jobId) => ipcRenderer.invoke('export:finalize', { jobId }), abortExport: (jobId) => ipcRenderer.invoke('export:abort', { jobId }),
}))
