import { vi } from 'vitest';

export function gpuFixture() {
  const constants = [
    'VERTEX_SHADER',
    'FRAGMENT_SHADER',
    'COMPILE_STATUS',
    'LINK_STATUS',
    'ARRAY_BUFFER',
    'DYNAMIC_DRAW',
    'FLOAT',
    'TEXTURE0',
    'TEXTURE_2D',
    'TEXTURE_WRAP_S',
    'TEXTURE_WRAP_T',
    'CLAMP_TO_EDGE',
    'TEXTURE_MIN_FILTER',
    'TEXTURE_MAG_FILTER',
    'LINEAR',
    'NEAREST',
    'UNPACK_FLIP_Y_WEBGL',
    'UNPACK_PREMULTIPLY_ALPHA_WEBGL',
    'RGBA',
    'UNSIGNED_BYTE',
    'MAX_TEXTURE_SIZE',
    'ONE',
    'ONE_MINUS_SRC_ALPHA',
    'FRAMEBUFFER',
    'COLOR_ATTACHMENT0',
    'FRAMEBUFFER_COMPLETE',
    'TRIANGLE_STRIP',
    'BLEND',
    'SCISSOR_TEST',
    'COLOR_BUFFER_BIT',
    'QUERY_RESULT_AVAILABLE',
    'QUERY_RESULT',
  ];
  const methods = [
    'shaderSource',
    'compileShader',
    'deleteShader',
    'attachShader',
    'linkProgram',
    'deleteProgram',
    'deleteBuffer',
    'deleteTexture',
    'useProgram',
    'bindBuffer',
    'bindTexture',
    'bindFramebuffer',
    'framebufferTexture2D',
    'bufferData',
    'enableVertexAttribArray',
    'vertexAttribPointer',
    'activeTexture',
    'uniform1i',
    'blendFunc',
    'texParameteri',
    'pixelStorei',
    'texImage2D',
    'viewport',
    'bufferSubData',
    'uniform2f',
    'drawArrays',
    'uniform4f',
    'uniform4fv',
    'uniform1f',
    'disable',
    'enable',
    'scissor',
    'clearColor',
    'clear',
    'deleteFramebuffer',
    'beginQuery',
    'endQuery',
    'deleteQuery',
    'vertexAttribDivisor',
    'drawArraysInstanced',
  ];
  const base = Object.fromEntries([
    ...constants.map((key, index) => [key, index + 1]),
    ...methods.map((key) => [key, vi.fn()]),
  ]);
  const mock = {
    ...base,
    createShader: vi.fn(() => ({})),
    createProgram: vi.fn(() => ({})),
    createBuffer: vi.fn(() => ({})),
    createTexture: vi.fn(() => ({})),
    createFramebuffer: vi.fn(() => ({})),
    createQuery: vi.fn(() => ({})),
    getShaderParameter: vi.fn(() => true),
    getProgramParameter: vi.fn(() => true),
    getShaderInfoLog: vi.fn(() => 'compile failed'),
    getProgramInfoLog: vi.fn(() => 'link failed'),
    getUniformLocation: vi.fn(() => ({})),
    getAttribLocation: vi.fn((_program: unknown, name: string) =>
      ['a_position', 'a_uv', 'a_rect', 'a_color', 'a_crop', 'a_texture'].indexOf(name),
    ),
    isContextLost: vi.fn(() => false),
    getExtension: vi.fn(() => ({ TIME_ELAPSED_EXT: 1001, GPU_DISJOINT_EXT: 1002 })),
    getParameter: vi.fn((key: number) => (key === base.MAX_TEXTURE_SIZE ? 4096 : false)),
    getQueryParameter: vi.fn((_query: unknown, key: number) => (key === base.QUERY_RESULT_AVAILABLE ? true : 1000000)),
    checkFramebufferStatus: vi.fn(() => base.FRAMEBUFFER_COMPLETE),
  };
  const gl = mock as unknown as WebGL2RenderingContext;
  const events = new EventTarget();
  const canvas = {
    width: 1,
    height: 1,
    getContext: vi.fn(() => gl),
    addEventListener: events.addEventListener.bind(events),
    removeEventListener: events.removeEventListener.bind(events),
    dispatchEvent: events.dispatchEvent.bind(events),
  } as unknown as OffscreenCanvas;
  return { gl, mock, canvas };
}
