<script setup lang="ts">
import { computed } from 'vue'
import ColorPicker from '~/ui/ColorPicker/ColorPicker.vue'
import Input from '~/ui/input/Input.vue'
import Slider from '~/ui/slider/Slider.vue'
import ButtonGroup from '~/ui/button/ButtonGroup.vue'
import Select from '~/ui/select/Select.vue'
import Button from '~/ui/button/Button.vue'
import { Type, Sparkles, Trash2, AlignCenter } from '@lucide/vue'
import type { CaptionCompositionLayer } from '../../composition/composition-types'

const props = defineProps<{
  layer: CaptionCompositionLayer | null;
}>()

const emit = defineEmits<{
  (event: 'update', layer: CaptionCompositionLayer): void;
  (event: 'delete', layerId: string): void;
}>()

const updateStyle = (key: keyof CaptionCompositionLayer['caption']['style'], value: any) => {
  if (!props.layer) return
  emit('update', {
    ...props.layer,
    caption: {
      ...props.layer.caption,
      style: {
        ...props.layer.caption.style,
        [key]: value,
      },
    },
  })
}

const handleCustomTextUpdate = (value: string) => {
  updateStyle('customText', value)
}

const updateWord = (sentenceId: string, index: number, key: 'text' | 'startMs' | 'endMs', value: string) => {
  if (!props.layer) return
  const sentences = props.layer.caption.sentences.map((sentence) =>
    sentence.id !== sentenceId
      ? sentence
      : (() => {
          const words = sentence.words.map((word, wordIndex) =>
            wordIndex === index ? { ...word, [key]: key === 'text' ? value : Number(value) } : word
          )
          return {
            ...sentence,
            words,
            text: words.map((w) => w.text).join(' '),
            startMs: words[0]?.startMs || 0,
            endMs: words.at(-1)?.endMs || 0,
          }
        })()
  )
  emit('update', {
    ...props.layer,
    startMs: sentences[0]?.startMs || props.layer.startMs,
    endMs: sentences.at(-1)?.endMs || props.layer.endMs,
    caption: { ...props.layer.caption, sentences },
  })
}

const shadowDirectionOptions = [
  { value: 'all', label: 'All around' },
  { value: 'bottom', label: 'Bottom' },
  { value: 'bottom-right', label: 'Bottom Right' },
  { value: 'top-left', label: 'Top Left' },
]

const placementOptions = [
  { value: 'top', label: 'Top' },
  { value: 'center', label: 'Center' },
  { value: 'bottom', label: 'Bottom' },
]
</script>

<template>
  <div class="caption-clip-panel">
    <template v-if="layer">
      <!-- AI Badge Header -->
      <div v-if="layer.isAiGenerated" class="ai-badge-header">
        <Sparkles :size="14" class="ai-badge-icon" />
        <span>Generated by AI (Whisper)</span>
      </div>

      <!-- 1. Text & Content Section -->
      <section class="prop-section">
        <h4 class="section-title"><Type :size="14" /> Display Text</h4>
        <div class="field-group">
          <label class="field-label">Custom Override Text</label>
          <Input
            :model-value="layer.caption.style.customText ?? ''"
            placeholder="Type custom text..."
            size="md"
            @update:model-value="handleCustomTextUpdate(String($event))"
          />
        </div>
      </section>

      <!-- 2. Typography & Appearance -->
      <section class="prop-section">
        <h4 class="section-title">Typography & Style</h4>
        
        <div class="field-grid-2">
          <div class="field-group">
            <label class="field-label">Text Color</label>
            <ColorPicker
              :model-value="layer.caption.style.color || '#ffffff'"
              @update:model-value="updateStyle('color', $event)"
            />
          </div>
          <div class="field-group">
            <label class="field-label">Placement</label>
            <ButtonGroup
              :items="placementOptions"
              :model-value="layer.caption.style.placement || 'bottom'"
              size="xs"
              @update:model-value="updateStyle('placement', $event)"
            />
          </div>
        </div>

        <div class="field-group">
          <div class="slider-header">
            <span class="field-label">Font Size</span>
            <span class="slider-value">{{ layer.caption.style.fontSize || 32 }}px</span>
          </div>
          <Slider
            :model-value="layer.caption.style.fontSize || 32"
            :min="16"
            :max="120"
            :step="1"
            @update:model-value="updateStyle('fontSize', $event)"
          />
        </div>

        <div class="field-group">
          <div class="slider-header">
            <span class="field-label">Backdrop Blur / Box</span>
            <span class="slider-value">{{ layer.caption.style.backdropBlur || 0 }}px</span>
          </div>
          <Slider
            :model-value="layer.caption.style.backdropBlur || 0"
            :min="0"
            :max="40"
            :step="1"
            @update:model-value="updateStyle('backdropBlur', $event)"
          />
        </div>
      </section>

      <!-- 3. Shadow Effects -->
      <section class="prop-section">
        <h4 class="section-title">Text Shadow</h4>
        
        <div class="field-grid-2">
          <div class="field-group">
            <label class="field-label">Shadow Color</label>
            <ColorPicker
              :model-value="layer.caption.style.shadowColor || 'rgba(0, 0, 0, 0.75)'"
              @update:model-value="updateStyle('shadowColor', $event)"
            />
          </div>
          <div class="field-group">
            <label class="field-label">Direction</label>
            <Select
              :items="shadowDirectionOptions"
              :model-value="layer.caption.style.shadowDirection || 'bottom-right'"
              size="sm"
              @update:model-value="updateStyle('shadowDirection', $event)"
            />
          </div>
        </div>

        <div class="field-group">
          <div class="slider-header">
            <span class="field-label">Shadow Blur</span>
            <span class="slider-value">{{ layer.caption.style.shadowBlur || 0 }}px</span>
          </div>
          <Slider
            :model-value="layer.caption.style.shadowBlur || 0"
            :min="0"
            :max="50"
            :step="1"
            @update:model-value="updateStyle('shadowBlur', $event)"
          />
        </div>
      </section>

      <!-- 4. Word-by-Word Editor (if transcription sentences exist) -->
      <section v-if="layer.caption.sentences.length" class="prop-section">
        <h4 class="section-title">Word Timings & Editing</h4>
        <div
          v-for="sentence in layer.caption.sentences"
          :key="sentence.id"
          class="sentence-box"
        >
          <p class="sentence-text">{{ sentence.text }}</p>
          <div
            v-for="(word, index) in sentence.words"
            :key="`${sentence.id}-${index}`"
            class="word-row"
          >
            <Input
              :model-value="word.text"
              size="sm"
              @update:model-value="updateWord(sentence.id, index, 'text', String($event))"
            />
            <Input
              :model-value="word.startMs"
              type="number"
              size="sm"
              @update:model-value="updateWord(sentence.id, index, 'startMs', String($event))"
            />
            <Input
              :model-value="word.endMs"
              type="number"
              size="sm"
              @update:model-value="updateWord(sentence.id, index, 'endMs', String($event))"
            />
          </div>
        </div>
      </section>

      <!-- Sticky Danger Delete Action -->
      <div class="danger-zone">
        <Button
          variant="danger"
          size="sm"
          :icon="Trash2"
          class="w-full"
          @click="emit('delete', layer.id)"
        >
          Delete Caption Clip
        </Button>
      </div>
    </template>
  </div>
</template>

<style scoped>
.caption-clip-panel {
  display: flex;
  flex-direction: column;
  gap: 18px;
  padding-bottom: 24px;
}

.ai-badge-header {
  display: flex;
  align-items: center;
  gap: 6px;
  background: rgba(99, 102, 241, 0.12);
  border: 1px solid rgba(99, 102, 241, 0.25);
  color: var(--color-primary);
  padding: 6px 12px;
  border-radius: var(--radius-sm);
  font-size: 11px;
  font-weight: 700;
}

.ai-badge-icon {
  color: var(--color-primary);
}

.prop-section {
  display: flex;
  flex-direction: column;
  gap: 12px;
  background: var(--color-bg-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  padding: 14px;
}

.section-title {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  font-weight: 700;
  color: var(--text-primary);
  margin: 0;
}

.field-group {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.field-grid-2 {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
  align-items: end;
}

.field-label {
  font-size: 10px;
  font-weight: 700;
  color: var(--text-secondary);
  text-transform: uppercase;
  letter-spacing: 0.03em;
}

.slider-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.slider-value {
  font-size: 11px;
  font-family: monospace;
  font-weight: 700;
  color: var(--color-primary-light, #ff8a5c);
}

.sentence-box {
  display: flex;
  flex-direction: column;
  gap: 6px;
  padding-top: 8px;
  border-top: 1px solid var(--color-border);
}

.sentence-text {
  font-size: 11px;
  font-weight: 700;
  color: var(--text-primary);
  margin: 0;
}

.word-row {
  display: grid;
  grid-template-columns: 1fr 58px 58px;
  gap: 4px;
}

.danger-zone {
  position: sticky;
  bottom: 0;
  margin-top: auto;
  padding-top: 12px;
  background: var(--color-bg-element);
  z-index: 10;
}

.w-full {
  width: 100%;
}
</style>
