<script setup lang="ts">
import { computed } from 'vue'
import ColorPicker from '~/ui/ColorPicker/ColorPicker.vue'
import Input from '~/ui/input/Input.vue'
import BigSlider from '~/ui/slider/BigSlider.vue'
import Select from '~/ui/select/Select.vue'
import Button from '~/ui/button/Button.vue'
import { Type, Sparkles, Trash2, Box, Moon } from '@lucide/vue'
import type { CaptionCompositionLayer } from '../../composition/composition-types'

const props = defineProps<{
  layer: CaptionCompositionLayer | null;
}>()

const emit = defineEmits<{
  (event: 'update', layer: CaptionCompositionLayer): void;
  (event: 'delete', layerId: string): void;
}>()

const captionStyle = computed(() => ({
  color: '#ffffff',
  fontSize: 32,
  shadowColor: 'rgba(0, 0, 0, 0.75)',
  shadowBlur: 0,
  shadowDirection: 'bottom-right',
  placement: 'bottom',
  boxColor: 'rgba(15, 23, 42, 0.75)',
  boxPadding: 16,
  boxRadius: 10,
  ...props.layer?.caption?.style,
}))

const sentences = computed(() => props.layer?.caption?.sentences ?? [])

const updateStyle = (key: string, value: any) => {
  if (!props.layer) return
  const currentCaption = props.layer.caption ?? { sentences: [], style: {} as any }
  emit('update', {
    ...props.layer,
    caption: {
      ...currentCaption,
      style: {
        ...currentCaption.style,
        [key]: value,
      },
    },
  })
}

const handleCustomTextUpdate = (value: string) => {
  updateStyle('customText', value)
}

const updateWord = (sentenceId: string, index: number, key: 'text' | 'startMs' | 'endMs', value: string) => {
  if (!props.layer || !props.layer.caption?.sentences) return
  const updatedSentences = props.layer.caption.sentences.map((sentence) =>
    sentence.id !== sentenceId
      ? sentence
      : (() => {
          const words = sentence.words.map((word, wordIndex) =>
            wordIndex === index ? { ...word, [key]: key === 'text' ? value : Number(value) } : word
          )
          return {
            ...sentence,
            words,
            text: words.map((w) => w.text).join(' '),
            startMs: words[0]?.startMs || 0,
            endMs: words.at(-1)?.endMs || 0,
          }
        })()
  )
  emit('update', {
    ...props.layer,
    startMs: updatedSentences[0]?.startMs || props.layer.startMs,
    endMs: updatedSentences.at(-1)?.endMs || props.layer.endMs,
    caption: { ...props.layer.caption, sentences: updatedSentences },
  })
}

const shadowDirectionOptions = [
  { value: 'all', label: 'All around' },
  { value: 'bottom', label: 'Bottom' },
  { value: 'bottom-right', label: 'Bottom Right' },
  { value: 'top-left', label: 'Top Left' },
]
</script>

<template>
  <div class="caption-clip-panel">
    <template v-if="layer">
      <!-- AI Badge Header -->
      <div v-if="layer.isAiGenerated" class="ai-badge-header">
        <Sparkles :size="14" class="ai-badge-icon" />
        <span>Generated by AI (Whisper)</span>
      </div>

      <!-- 1. Display Text Section -->
      <div class="panel-group">
        <h4 class="group-title"><Type :size="14" /> Display Text</h4>
        <div class="field-group">
          <label class="field-label">Custom Override Text</label>
          <Input
            :model-value="captionStyle.customText ?? ''"
            placeholder="Type custom text..."
            size="md"
            @update:model-value="handleCustomTextUpdate(String($event))"
          />
        </div>
      </div>

      <div class="divider"></div>

      <!-- 2. Typography Section -->
      <div class="panel-group">
        <h4 class="group-title"><Type :size="14" /> Typography</h4>
        <div class="field-grid-2">
          <div class="field-group">
            <label class="field-label">Text Color</label>
            <ColorPicker
              :model-value="captionStyle.color || '#ffffff'"
              @update:model-value="updateStyle('color', $event)"
            />
          </div>
        </div>

        <BigSlider
          label="Font Size"
          :model-value="captionStyle.fontSize || 32"
          :min="12"
          :max="120"
          :step="1"
          :default-value="32"
          :format-value="(val) => `${val}px`"
          @update:model-value="updateStyle('fontSize', $event)"
        />
      </div>

      <div class="divider"></div>

      <!-- 3. Background Box Section -->
      <div class="panel-group">
        <h4 class="group-title"><Box :size="14" /> Background Box</h4>
        <div class="field-grid-2">
          <div class="field-group">
            <label class="field-label">Box Color</label>
            <ColorPicker
              :model-value="captionStyle.boxColor || 'rgba(15, 23, 42, 0.75)'"
              @update:model-value="updateStyle('boxColor', $event)"
            />
          </div>
        </div>

        <BigSlider
          label="Box Padding"
          :model-value="captionStyle.boxPadding ?? 16"
          :min="0"
          :max="60"
          :step="1"
          :default-value="16"
          :format-value="(val) => `${val}px`"
          @update:model-value="updateStyle('boxPadding', $event)"
        />

        <BigSlider
          label="Corner Radius"
          :model-value="captionStyle.boxRadius ?? 10"
          :min="0"
          :max="40"
          :step="1"
          :default-value="10"
          :format-value="(val) => `${val}px`"
          @update:model-value="updateStyle('boxRadius', $event)"
        />
      </div>

      <div class="divider"></div>

      <!-- 4. Text Shadow Section -->
      <div class="panel-group">
        <h4 class="group-title"><Moon :size="14" /> Text Shadow</h4>
        <div class="field-grid-2">
          <div class="field-group">
            <label class="field-label">Shadow Color</label>
            <ColorPicker
              :model-value="captionStyle.shadowColor || 'rgba(0, 0, 0, 0.75)'"
              @update:model-value="updateStyle('shadowColor', $event)"
            />
          </div>
          <div class="field-group">
            <label class="field-label">Direction</label>
            <Select
              :items="shadowDirectionOptions"
              :model-value="captionStyle.shadowDirection || 'bottom-right'"
              size="sm"
              @update:model-value="updateStyle('shadowDirection', $event)"
            />
          </div>
        </div>

        <BigSlider
          label="Shadow Blur"
          :model-value="captionStyle.shadowBlur || 0"
          :min="0"
          :max="50"
          :step="1"
          :default-value="0"
          :format-value="(val) => `${val}px`"
          @update:model-value="updateStyle('shadowBlur', $event)"
        />
      </div>

      <div class="divider" v-if="sentences.length"></div>

      <!-- 5. Word-by-Word Editor -->
      <div v-if="sentences.length" class="panel-group">
        <h4 class="group-title">Word Timings & Editing</h4>
        <div
          v-for="sentence in sentences"
          :key="sentence.id"
          class="sentence-box"
        >
          <p class="sentence-text">{{ sentence.text }}</p>
          <div
            v-for="(word, index) in sentence.words"
            :key="`${sentence.id}-${index}`"
            class="word-row"
          >
            <Input
              :model-value="word.text"
              size="sm"
              @update:model-value="updateWord(sentence.id, index, 'text', String($event))"
            />
            <Input
              :model-value="word.startMs"
              type="number"
              size="sm"
              @update:model-value="updateWord(sentence.id, index, 'startMs', String($event))"
            />
            <Input
              :model-value="word.endMs"
              type="number"
              size="sm"
              @update:model-value="updateWord(sentence.id, index, 'endMs', String($event))"
            />
          </div>
        </div>
      </div>

      <!-- Sticky Danger Delete Action -->
      <div class="danger-zone">
        <Button
          variant="danger"
          size="sm"
          :icon="Trash2"
          class="w-full"
          @click="emit('delete', layer.id)"
        >
          Delete Caption Clip
        </Button>
      </div>
    </template>
  </div>
</template>

<style scoped>
.caption-clip-panel {
  display: flex;
  flex-direction: column;
  gap: 16px;
  padding-bottom: 24px;
}

.ai-badge-header {
  display: flex;
  align-items: center;
  gap: 6px;
  background: rgba(99, 102, 241, 0.12);
  border: 1px solid rgba(99, 102, 241, 0.25);
  color: var(--color-primary);
  padding: 6px 12px;
  border-radius: var(--radius-sm);
  font-size: 11px;
  font-weight: 700;
}

.ai-badge-icon {
  color: var(--color-primary);
}

.panel-group {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.divider {
  height: 1px;
  background-color: var(--color-border);
  margin: 4px 0;
}

.group-title {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  font-weight: 700;
  color: var(--text-primary);
  margin: 0;
}

.field-group {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.field-grid-2 {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
  align-items: end;
}

.field-label {
  font-size: 10px;
  font-weight: 700;
  color: var(--text-secondary);
  text-transform: uppercase;
  letter-spacing: 0.03em;
}

.sentence-box {
  display: flex;
  flex-direction: column;
  gap: 6px;
  padding-top: 8px;
}

.sentence-text {
  font-size: 11px;
  font-weight: 700;
  color: var(--text-primary);
  margin: 0;
}

.word-row {
  display: grid;
  grid-template-columns: 1fr 58px 58px;
  gap: 4px;
}

.danger-zone {
  position: sticky;
  bottom: 0;
  margin-top: auto;
  padding-top: 12px;
  background: var(--color-bg-element);
  z-index: 10;
}

.w-full {
  width: 100%;
}
</style>
