use super::{Artifact, Feed, Snapshot, UpdateEvent};
use argui_updater::{InstallOutcome, Progress, ReleaseInfo, State, install::Format};
use serde_json::{Value, json};

/// Models one complete published release with the wire names generated by CI.
fn feed() -> Value {
    json!({
        "schemaVersion": 1,
        "version": "0.4.0",
        "notes": "Fixes for Beam",
        "platforms": {
            "linux-x86_64": {
                "url": "https://github.com/BeamRecorder/Beam/releases/download/0.4.0/Beam-0.4.0-linux-x64.AppImage",
                "sha256": "ab".repeat(32),
                "size": 256,
                "format": "app-image"
            }
        }
    })
}

/// Supplies release metadata for the native-to-Solid snapshot contract.
fn release() -> ReleaseInfo {
    ReleaseInfo {
        version: "0.4.0".into(),
        notes: "Fixes for Beam".into(),
    }
}

#[test]
fn feed_decodes_ci_names_semantic_version_and_optional_release_notes() {
    let value: Feed = serde_json::from_value(feed()).unwrap();
    assert_eq!(value.schema_version, 1);
    assert_eq!(value.version, semver::Version::new(0, 4, 0));
    assert_eq!(value.notes, "Fixes for Beam");
    assert_eq!(value.platforms.len(), 1);
    let package = &value.platforms["linux-x86_64"];
    assert_eq!(package.size, 256);
    assert_eq!(package.sha256, "ab".repeat(32));
    assert_eq!(package.format, Format::AppImage);

    let mut without_notes = feed();
    without_notes.as_object_mut().unwrap().remove("notes");
    assert!(
        serde_json::from_value::<Feed>(without_notes)
            .unwrap()
            .notes
            .is_empty()
    );
}

#[test]
fn feed_rejects_unknown_fields_missing_required_fields_and_wrong_types() {
    for patch in [
        json!({ "unknown": true }),
        json!({ "schema_version": 1 }),
        json!({ "schemaVersion": "1" }),
        json!({ "schemaVersion": -1 }),
        json!({ "version": "0.4" }),
        json!({ "version": false }),
        json!({ "notes": null }),
        json!({ "platforms": [] }),
    ] {
        let mut value = feed();
        value
            .as_object_mut()
            .unwrap()
            .extend(patch.as_object().unwrap().clone());
        assert!(serde_json::from_value::<Feed>(value).is_err(), "{patch}");
    }
    for missing in ["schemaVersion", "version", "platforms"] {
        let mut value = feed();
        value.as_object_mut().unwrap().remove(missing);
        assert!(
            serde_json::from_value::<Feed>(value).is_err(),
            "accepted feed without {missing}"
        );
    }
    for invalid in ["not JSON", "[]", "null", "{", "{}"] {
        assert!(serde_json::from_str::<Feed>(invalid).is_err(), "{invalid}");
    }
}

#[test]
fn artifact_schema_rejects_legacy_signatures_unknown_formats_and_invalid_field_types() {
    let valid = feed()["platforms"]["linux-x86_64"].clone();
    for patch in [
        json!({ "signature": "legacy signature" }),
        json!({ "format": "zip" }),
        json!({ "format": "appImage" }),
        json!({ "url": false }),
        json!({ "sha256": [] }),
        json!({ "size": -1 }),
        json!({ "size": 1.5 }),
        json!({ "size": "256" }),
    ] {
        let mut value = valid.clone();
        value
            .as_object_mut()
            .unwrap()
            .extend(patch.as_object().unwrap().clone());
        assert!(
            serde_json::from_value::<Artifact>(value).is_err(),
            "{patch}"
        );
    }
    for missing in ["url", "sha256", "size", "format"] {
        let mut value = valid.clone();
        value.as_object_mut().unwrap().remove(missing);
        assert!(
            serde_json::from_value::<Artifact>(value).is_err(),
            "accepted artifact without {missing}"
        );
    }
    let mut nested = feed();
    nested["platforms"]["linux-x86_64"]["unexpected"] = json!(true);
    assert!(serde_json::from_value::<Feed>(nested).is_err());
}

#[test]
fn snapshots_map_every_engine_phase_and_its_release_identity() {
    for (state, phase, version) in [
        (State::Idle, "idle", None),
        (State::Checking, "checking", None),
        (State::UpToDate, "upToDate", None),
        (State::Available(release()), "available", Some("0.4.0")),
        (
            State::Downloading {
                release: release(),
                progress: Progress::default(),
            },
            "downloading",
            Some("0.4.0"),
        ),
        (State::Verifying(release()), "verifying", Some("0.4.0")),
        (State::Ready(release()), "ready", Some("0.4.0")),
        (State::Installing(release()), "installing", Some("0.4.0")),
        (
            State::Installed {
                release: release(),
                outcome: InstallOutcome::InstallerLaunched,
            },
            "installed",
            Some("0.4.0"),
        ),
        (State::Cancelled(release()), "cancelled", Some("0.4.0")),
        (State::Failed("offline".into()), "failed", None),
    ] {
        let snapshot = Snapshot::from_state(&state);
        assert_eq!(snapshot.phase, phase, "{state:?}");
        assert_eq!(snapshot.version.as_deref(), version, "{state:?}");
        assert_eq!(snapshot.downloaded, 0, "{state:?}");
        assert_eq!(snapshot.total, None, "{state:?}");
        assert_eq!(snapshot.percent, None, "{state:?}");
        assert!(!snapshot.restart_required, "{state:?}");
    }
}

#[test]
fn downloading_snapshots_preserve_bytes_and_safe_determinate_or_unknown_progress() {
    for (downloaded, total, percent) in [
        (0, Some(256), Some(0.0)),
        (64, Some(256), Some(25.0)),
        (256, Some(256), Some(100.0)),
        (300, Some(256), Some(100.0)),
        (64, None, None),
        (64, Some(0), None),
        (u64::MAX, Some(u64::MAX), Some(100.0)),
    ] {
        let snapshot = Snapshot::from_state(&State::Downloading {
            release: release(),
            progress: Progress { downloaded, total },
        });
        assert_eq!(snapshot.phase, "downloading");
        assert_eq!(snapshot.version.as_deref(), Some("0.4.0"));
        assert_eq!(snapshot.downloaded, downloaded);
        assert_eq!(snapshot.total, total);
        assert_eq!(snapshot.percent, percent);
        assert!(snapshot.percent.is_none_or(f32::is_finite));
        assert_eq!(snapshot.error, None);
        assert!(!snapshot.restart_required);
    }
}

#[test]
fn failed_snapshots_expose_the_error_without_stale_release_or_progress() {
    let snapshot = Snapshot::from_state(&State::Failed("Échec du téléchargement".into()));
    assert_eq!(snapshot.phase, "failed");
    assert_eq!(snapshot.error.as_deref(), Some("Échec du téléchargement"));
    assert_eq!(snapshot.version, None);
    assert_eq!(snapshot.downloaded, 0);
    assert_eq!(snapshot.total, None);
    assert_eq!(snapshot.percent, None);
    assert!(!snapshot.restart_required);
}

#[test]
fn installed_snapshots_distinguish_restart_from_an_already_launched_installer() {
    for (outcome, restart_required) in [
        (InstallOutcome::RestartRequired, true),
        (InstallOutcome::InstallerLaunched, false),
    ] {
        let snapshot = Snapshot::from_state(&State::Installed {
            release: release(),
            outcome,
        });
        assert_eq!(snapshot.phase, "installed");
        assert_eq!(snapshot.version.as_deref(), Some("0.4.0"));
        assert_eq!(snapshot.restart_required, restart_required);
        assert_eq!(snapshot.error, None);
    }
}

#[test]
fn snapshot_and_broadcast_serialize_the_exact_solid_service_contract() {
    let snapshot = Snapshot::from_state(&State::Downloading {
        release: release(),
        progress: Progress {
            downloaded: 64,
            total: Some(256),
        },
    });
    let expected = json!({
        "phase": "downloading", "version": "0.4.0", "downloaded": 64,
        "total": 256, "percent": 25.0, "error": null, "restartRequired": false
    });
    assert_eq!(serde_json::to_value(&snapshot).unwrap(), expected);
    let event = UpdateEvent {
        r#type: "updaterState",
        update: &snapshot,
    };
    assert_eq!(
        serde_json::to_value(&event).unwrap(),
        json!({ "type": "updaterState", "update": expected })
    );
}
