import { vi } from 'vitest'

export const captureMock = {
  discover: vi.fn(),
  getSources: vi.fn(),
  hideScreenRegionOverlay: vi.fn(),
  setWindowVisible: vi.fn(),
  selectScreenRegion: vi.fn(),
  startRecording: vi.fn(),
  stop: vi.fn(),
  discardRecording: vi.fn(),
  setSize: vi.fn(),
  close: vi.fn(),
  minimize: vi.fn(),
  listProjects: vi.fn(),
  createProject: vi.fn(),
  renameProject: vi.fn(),
  deleteProject: vi.fn(),
  configureCameraOverlay: vi.fn(),
  setCameraOverlayActive: vi.fn(),
  getCameraOverlayState: vi.fn().mockResolvedValue(null),
  onCameraOverlayState: vi.fn().mockReturnValue(() => undefined),
  onCameraOverlayHover: vi.fn().mockReturnValue(() => undefined),
  onCameraShadow: vi.fn().mockReturnValue(() => undefined),
  getPreferences: vi.fn().mockResolvedValue({
    schemaVersion: 2,
    theme: 'system',
    recordingBar: { visibility: 'always' },
    devices: {},
    shortcuts: {},
    backgroundPresets: { colors: [], gradients: [] },
    extras: {},
  }),
  updatePreferences: vi.fn().mockImplementation(async (patch) => ({
    schemaVersion: 2,
    theme: patch.theme || 'system',
    recordingBar: { visibility: 'always' },
    devices: {},
    shortcuts: {},
    backgroundPresets: { colors: [], gradients: [] },
    extras: {},
  })),
  resetPreferences: vi.fn(),
  onPreferencesChanged: vi.fn().mockReturnValue(() => undefined),
  onPreferenceShortcut: vi.fn().mockReturnValue(() => undefined),
  showTeleprompter: vi.fn(),
  hideTeleprompter: vi.fn(),
  toggleTeleprompterVisibility: vi.fn(),
  setTeleprompterSession: vi.fn(),
  onTeleprompterShortcut: vi.fn().mockReturnValue(() => undefined),
  onTeleprompterSession: vi.fn().mockReturnValue(() => undefined),
  onTeleprompterVisibility: vi.fn().mockReturnValue(() => undefined),
  saveSessionTeleprompter: vi.fn().mockResolvedValue(null),
  getSessionTeleprompter: vi.fn().mockResolvedValue(null),
  getUpdateState: vi
    .fn()
    .mockResolvedValue({
      status: 'unsupported',
      currentVersion: '0.1.0',
      availableVersion: null,
      percent: null,
      message: null,
    }),
  checkForUpdates: vi.fn(),
  downloadUpdate: vi.fn(),
  quitAndInstallUpdate: vi.fn(),
  openUpdateChangelog: vi.fn(),
  onUpdateState: vi.fn().mockReturnValue(() => undefined),
}
