import { expect, it } from 'vitest';
import { Batch } from '../src/batch.ts';
import { number, seconds } from '../src/time.ts';
import { assertContract } from '../src/validation.ts';
const id = '00000000-0000-4000-8000-000000000001';
it('builds typed sequential references across inserts, effects and animation', () => {
  const batch = new Batch();
  const track = batch.edit({ type: 'addTrack', name: 'Video', kind: 'video' }, 'track');
  const clip = batch.insert(id, track, 0, 1000, 0, 'clip');
  const effect = batch.effect(clip, 'beam.transform', { rotation: number(10) }, 1, 'transform');
  batch.parameter(clip, effect, 'rotation', number(20));
  batch.duplicateEffect(clip, effect);
  batch.transition(clip, id, 100);
  batch.generator(track, 'beam.solid', 1000, 500);
  batch.keyframeAt(clip, effect, 'rotation', 'clipLocal', seconds(1), { kind: 'number', value: 20 });
  batch.paste([id], id, track, 2000);
  batch.pasteMapped([id], id, { [id]: track }, 2500);
  batch.register({ id: 'example', namespace: 'example', sha256: 'a'.repeat(64), version: 1, definitions: [], presets: [] });
  batch.applyPreset({ kind: 'effect', clipId: id, instanceId: id }, 'beam.opacity.fadeIn');
  for (const command of batch.commands) assertContract('Command', command);
  expect(track).toEqual({ createdBy: 'track' });
  expect(batch.commands).toHaveLength(12);
  expect(batch.commands[1]?.operation).toMatchObject({ type: 'insert', track: { createdBy: 'track' } });
});
it('isolates caller data and rejects ambiguous command IDs', () => {
  const batch = new Batch(); const binding = number(1);
  batch.effect(id, 'beam.gain', { volume: binding }, 1, 'same');
  if (binding.kind === 'constant' && binding.value.kind === 'number') binding.value.value = 5;
  expect(batch.commands[0]?.operation).toMatchObject({ parameters: { volume: { value: { value: 1 } } } });
  expect(() => batch.edit({ type: 'undo' }, 'same')).toThrow();
  expect(() => batch.edit({ type: 'undo' }, '')).toThrow();
  expect(batch.commands).toHaveLength(1);
  expect(batch.result('same', 2)).toEqual({ createdBy: 'same', index: 2 });
  expect(() => batch.result('missing')).toThrow();
  expect(() => batch.result('same', -1)).toThrow();
  expect(() => batch.result('same', 0.5)).toThrow();
});
it('builds track and sequence stacks with explicit scopes, versions and earlier result IDs',()=>{
  const batch=new Batch();
  const lane=batch.edit({type:'addTrack',name:'Layer',kind:'video'},'lane');
  const opacity=batch.trackEffect(lane,'beam.opacity',{opacity:number(0.75)},2,'lane-opacity');
  const transform=batch.sequenceEffect(id,'beam.transform');
  batch.scopedParameter({kind:'track',track:lane},opacity,'opacity',number(0.5));
  batch.scoped({kind:'sequence',sequenceId:id},{type:'keyframeAdd',instance:transform,parameter:'rotation',time:seconds(1),value:{kind:'number',value:20},interpolation:{kind:'linear'}});
  batch.trackEffect(id,'custom.effect',{},1);
  batch.sequenceEffect(id,'custom.effect',{},1);
  batch.applyPreset({kind:'track',trackId:id,instanceId:id},'custom.preset',1);
  batch.applyPreset({kind:'sequence',sequenceId:id,instanceId:id},'custom.preset',1);
  for(const command of batch.commands)assertContract('Command',command);
  expect(batch.commands[1]?.operation).toMatchObject({type:'scopedEffect',target:{kind:'track',track:{createdBy:'lane'}},action:{type:'add',definitionVersion:2}});
  expect(batch.commands[2]?.operation).toMatchObject({target:{kind:'sequence',sequenceId:id},action:{definitionVersion:2}});
  expect(batch.commands[3]?.operation).toMatchObject({action:{type:'parameterSet',instance:{createdBy:'lane-opacity'}}});
  expect(batch.commands[5]?.operation).toMatchObject({action:{definitionVersion:1}});
});
