import type { EditorPropertyGroup } from './editor-search-types';

export const EDITOR_PROPERTY_GROUPS: readonly EditorPropertyGroup[] = [
  { namespace: 'ScreenshotComposition', tab: 'clip', clipOnly: true, modes: ['screenshot'], keys: ['name'] },
  {
    namespace: 'CanvasPanel',
    tab: 'canvas',
    keys: [
      'backgroundType',
      'image',
      'video',
      'color',
      'gradient',
      'blur',
      'removeBackground',
      'watermark',
      'watermarkText',
      'showBeamLogo',
      'watermarkPosition',
      'watermarkSize',
      'watermarkShadow',
      'watermarkBackgroundColor',
      'watermarkBackgroundOpacity',
      'watermarkBackgroundRadius',
      'watermarkBackgroundPadding',
    ],
  },
  {
    namespace: 'ClipPropertiesPanel',
    kinds: ['screen', 'video', 'image', 'webcam'],
    tab: 'clip',
    clipOnly: true,
    keys: [
      'placement',
      'horizontal',
      'vertical',
      'size',
      'cornerRadius',
      'dropShadow',
      'shadowColor',
      'shadowBlur',
      'shadowStyle',
      'direction',
      'mirroring',
      'mirrorHorizontally',
      'mirrorVertically',
      'speedBoost',
      'playbackSpeed',
      'crop',
    ],
  },
  {
    namespace: 'CanvasPanel',
    kinds: ['color', 'shape'],
    tab: 'clip',
    section: 'appearance',
    clipOnly: true,
    keys: [
      'colorLayerOpacity',
      'colorLayerCornerRadius',
      'colorLayerShadow',
      'colorLayerBackdropBlur',
      'shapeFamily',
      'shapeCornerRadius',
      'arrowThickness',
      'arrowHeadSize',
      'shapeRotation',
      'shapePreset',
      'fillColor',
      'borderColor',
      'borderWidth',
      'itemOpacity',
      'shadowColor',
      'shadowBlur',
    ],
  },
  {
    namespace: 'Elements',
    kinds: ['shape'],
    tab: 'clip',
    clipOnly: true,
    section: 'text',
    keys: ['editText', 'verticalAlignment', 'textPadding'],
  },
  {
    namespace: 'Elements',
    kinds: ['shape'],
    tab: 'clip',
    clipOnly: true,
    section: 'appearance',
    keys: ['shapeLibrary', 'strokeColor', 'strokeWidth', 'smoothing'],
  },
  {
    namespace: 'CaptionClipPanel',
    section: 'text',
    kinds: ['caption', 'shape'],
    tab: 'clip',
    clipOnly: true,
    keys: [
      'font',
      'fontSize',
      'textColor',
      'textAlignment',
      'backgroundColor',
      'backgroundOpacity',
      'shadowColor',
      'shadowBlur',
    ],
  },
  {
    namespace: 'BlurPropertiesPanel',
    kinds: ['blur'],
    tab: 'clip',
    clipOnly: true,
    keys: [
      'mode',
      'shape',
      'appearance',
      'blurRadius',
      'frostIntensity',
      'pixelSize',
      'cornerRadius',
      'strength',
      'feather',
      'tintOpacity',
      'color',
    ],
  },
  {
    namespace: 'AudioClipPropertiesPanel',
    kinds: ['audio'],
    tab: 'clip',
    clipOnly: true,
    videoOnly: true,
    keys: ['volume', 'normalize'],
  },
  {
    namespace: 'Highlight',
    tab: 'clip',
    kinds: ['blur'],
    clipOnly: true,
    modes: ['screenshot'],
    keys: ['opacity', 'highlightOpacity', 'highlightColor'],
  },
  {
    namespace: 'AppearanceSettings',
    tab: 'settings',
    modes: ['screenshot'],
    keys: ['themeMode', 'primaryColor', 'secondaryColor', 'cornerRadius', 'surfaceTone'],
  },
  {
    namespace: 'ZoomPanel',
    tab: 'zoom',
    videoOnly: true,
    keys: [
      'cameraFollow',
      'safeZone',
      'responsiveness',
      'straightPaths',
      'mode',
      'projection',
      'tiltIntensity',
      'tiltHorizontal',
      'tiltVertical',
      'tiltPreset',
      'magnification',
      'zoomLevel',
      'motionBlur',
      'motionBlurIntensity',
    ],
  },
  {
    namespace: 'CursorPanel',
    tab: 'cursor',
    videoOnly: true,
    keys: [
      'cursorStyle',
      'cursorSize',
      'autoHideCursor',
      'autoHideDelay',
      'autoHideFadeDuration',
      'cursorColor',
      'dropShadow',
      'direction',
      'clickSpring',
      'springIntensity',
      'clickRippleEffect',
      'rippleStyle',
      'rippleSize',
      'rippleColor',
      'cursorMotion',
      'motionPreset',
      'cursorSmoothing',
      'springMassMultiplier',
      'stopSpring',
      'stopSpringStrength',
      'motionBlur',
      'cursorPack',
      'shadowBlur',
      'shadowColor',
    ],
  },
  {
    namespace: 'CursorPanel',
    tab: 'clip',
    kinds: ['cursor'],
    clipOnly: true,
    keys: [
      'cursorStyle',
      'cursorSize',
      'cursorColor',
      'dropShadow',
      'shadowBlur',
      'shadowColor',
      'direction',
      'cursorPack',
    ],
  },
  { namespace: 'CanvasPanel', tab: 'clip', kinds: ['cursor'], clipOnly: true, keys: ['shapeRotation'] },
  {
    namespace: 'CaptionPanel',
    tab: 'caption',
    videoOnly: true,
    keys: ['audioSource', 'whisperModel', 'generateCaptions', 'exportTranscript'],
  },
  {
    namespace: 'AudioPanel',
    tab: 'audio',
    videoOnly: true,
    keys: ['systemVolume', 'microphoneVolume', 'normalizeAll'],
  },
  {
    namespace: 'SettingsPanel',
    tab: 'settings',
    keys: ['themeMode', 'language', 'devMode', 'recorderTool', 'sysInfoTool', 'devToolsTool'],
  },
];
