import { vi } from 'vitest';
import type { ScreenRegionSelectionOptions, ScreenRegionSelectionResult } from '../../../api/types/screen-region';
import type { ProjectCatalogPage, ProjectCatalogRequest } from '../../../api/types/project-catalog';
import type { CaptureProject } from '@beam/engine/capture/capture-session';

const listProjects = vi.fn();

export const captureMock = {
  onProjectLocationsChanged: vi.fn(() => vi.fn()),
  openHudSettings: vi.fn().mockResolvedValue(true),
  openHudProjects: vi.fn().mockResolvedValue(true),
  notifyScreenRegionReady: vi.fn(),
  platform: 'darwin',
  devCrossplatform: false,
  selectCaptureSource: vi.fn().mockImplementation(async (kind) => ({
    kind,
    id: kind === 'screen' ? 'native:display:1' : 'window:42:0',
    development: false,
    source: {
      id: kind === 'screen' ? 'native:display:1' : 'window:42:0',
      kind,
      name: 'Selection',
      app: '',
      detail: '',
      aspect: 1.6,
    },
  })),
  onCountdownCancelled: vi.fn(() => vi.fn()),
  setCountdown: vi.fn().mockResolvedValue(undefined),
  discover: vi.fn(),
  getSources: vi.fn(),
  hideScreenRegionOverlay: vi.fn(),
  setWindowVisible: vi.fn(),
  setInteractive: vi.fn(),
  getDisplayBounds: vi.fn(),
  inputAccessStatus: vi.fn().mockResolvedValue({
    state: 'available',
    canRequest: false,
    clicks: true,
    shortcuts: true,
    recordsText: false,
  }),
  requestInputAccess: vi.fn().mockResolvedValue({
    state: 'available',
    canRequest: false,
    clicks: true,
    shortcuts: true,
    recordsText: false,
  }),
  selectScreenRegion: vi.fn<(options: ScreenRegionSelectionOptions) => Promise<ScreenRegionSelectionResult | null>>(),
  startRecording: vi.fn(),
  stop: vi.fn(),
  discardRecording: vi.fn(),
  setSize: vi.fn(),
  resizeHudPopover: vi.fn().mockResolvedValue(268),
  close: vi.fn(),
  quit: vi.fn(),
  minimize: vi.fn(),
  listProjects,
  listProjectsPage: vi.fn<(request?: ProjectCatalogRequest) => Promise<ProjectCatalogPage>>(async (request = {}) => {
    const projects = (await listProjects()) as CaptureProject[];
    const query = request.query?.trim().toLowerCase() ?? '';
    const matches = projects.filter((project) => project.name.toLowerCase().includes(query));
    return { projects: matches, total: matches.length, nextCursor: null };
  }),
  createProject: vi.fn(),
  renameProject: vi.fn(),
  deleteProject: vi.fn(),
  revealProject: vi.fn(),
  configureCameraOverlay: vi.fn(),
  setCameraOverlayActive: vi.fn(),
  getCameraOverlayState: vi.fn().mockResolvedValue(null),
  onCameraOverlayState: vi.fn().mockReturnValue(() => undefined),
  onCameraOverlayHover: vi.fn().mockReturnValue(() => undefined),
  onCameraShadow: vi.fn().mockReturnValue(() => undefined),
  getPreferences: vi.fn().mockResolvedValue({
    schemaVersion: 3,
    theme: 'system',
    recordingBar: { visibility: 'always' },
    recordingInteractions: { enabled: false, noticeDismissed: false },
    alwaysOnTop: true,
    devices: {},
    shortcuts: {},
    backgroundPresets: { colors: [], gradients: [] },
    extras: {},
  }),
  updatePreferences: vi.fn().mockImplementation(async (patch) => ({
    schemaVersion: 3,
    theme: patch.theme || 'system',
    recordingBar: { visibility: 'always' },
    recordingInteractions: { enabled: false, noticeDismissed: false },
    alwaysOnTop: patch.alwaysOnTop !== undefined ? patch.alwaysOnTop : true,
    devices: {},
    shortcuts: {},
    backgroundPresets: { colors: [], gradients: [] },
    extras: {},
  })),
  resetPreferences: vi.fn(),
  onPreferencesChanged: vi.fn().mockReturnValue(() => undefined),
  onPreferenceShortcut: vi.fn().mockReturnValue(() => undefined),
  showTeleprompter: vi.fn(),
  hideTeleprompter: vi.fn(),
  toggleTeleprompterVisibility: vi.fn(),
  setTeleprompterSession: vi.fn(),
  onTeleprompterShortcut: vi.fn().mockReturnValue(() => undefined),
  onTeleprompterSession: vi.fn().mockReturnValue(() => undefined),
  onTeleprompterVisibility: vi.fn().mockReturnValue(() => undefined),
  saveSessionTeleprompter: vi.fn().mockResolvedValue(null),
  getSessionTeleprompter: vi.fn().mockResolvedValue(null),
  getUpdateState: vi.fn().mockResolvedValue({
    status: 'unsupported',
    currentVersion: '0.1.0',
    availableVersion: null,
    percent: null,
    message: null,
  }),
  checkForUpdates: vi.fn(),
  downloadUpdate: vi.fn(),
  quitAndInstallUpdate: vi.fn(),
  openUpdateChangelog: vi.fn(),
  onUpdateState: vi.fn().mockReturnValue(() => undefined),
};
